choco install -y 7zip.install
choco install -y ag
choco install -y awscli
choco install -y AWSTools.Powershell
choco install -y clink
choco install -y ConEmu
choco install -y curl
choco install -y dropbox
choco install -y Emacs
choco install -y fiddler
choco install -y Firefox
choco install -y git.install -params '"/GitAndUnixToolsOnPath"'
choco install -y GoogleChrome
choco install -y kitty
choco install -y nmap
choco install -y nodejs.install
choco install -y notepadplusplus.install
choco install -y P4Merge
choco install -y paint.net
choco install -y pidgin
choco install -y pip
choco install -y putty
choco install -y python
choco install -y python3
choco install -y rdcman
choco install -y scriptcs
choco install -y sharpkeys
choco install -y spotify
choco install -y sublimetext3
choco install -y sysinternals
choco install -y UrlRewrite
choco install -y VisualStudioCode
choco install -y vlc
choco install -y Wget
choco install -y windirstat
choco install -y slack
choco install -y 1password
choco install -y sqlyog
