cinst 7zip.install -y
cinst ag -y
cinst autohotkey.portable -y
cinst autoit.commandline -y
cinst awscli -y
cinst AWSTools.Powershell -y
cinst chocolatey -y
cinst clink -y
cinst CloudBerryExplorer.AmazonS3 -y
cinst ConEmu -y
cinst curl -y
cinst dropbox -y
cinst Emacs -y
cinst Evernote -y
cinst fiddler -y
cinst Firefox -y
cinst git -y
cinst git.install -y
cinst gitextensions -y
cinst GoogleChrome -y
cinst kdiff3 -y
cinst kitty -y
cinst linqpad5.install -y
cinst nmap -y
cinst nodejs.install -y
cinst notepadplusplus.install -y
cinst P4Merge -y
cinst paint.net -y
cinst pidgin -y
cinst pip -y
cinst PowerShell -y
cinst putty -y
cinst putty.portable -y
cinst python -y
cinst python3 -y
cinst rdcman -y
cinst scriptcs -y
cinst sharpkeys -y
cinst skype -y
cinst spotify -y
cinst sublimetext3 -y
cinst sysinternals -y
cinst todoist -y
cinst UrlRewrite -y
cinst VisualStudioCode -y
cinst vlc -y
cinst Wget -y
cinst windirstat -y
cinst wunderlist -y
