choco install -y 7zip.install
choco install -y ag
choco install -y autohotkey.portable
choco install -y autoit.commandline
choco install -y awscli
choco install -y AWSTools.Powershell
choco install -y chocolatey
choco install -y chocolatey-core.extension
choco install -y clink
choco install -y ConEmu
choco install -y curl
choco install -y DotNet4.5.2
choco install -y dropbox
choco install -y Emacs
choco install -y fiddler
choco install -y fiddler4
choco install -y Firefox
choco install -y git.install -params '"/GitAndUnixToolsOnPath"'
choco install -y GoogleChrome
choco install -y hackfont
choco install -y html-tidy
choco install -y nmap
choco install -y nodejs.install
choco install -y notepadplusplus.install
choco install -y P4Merge
choco install -y pidgin
#choco install -y pip
choco install -y PowerShell
choco install -y putty
choco install -y putty.portable
#choco install -y python
#choco install -y python3
choco install -y rdcman
choco install -y redis-64
choco install -y ruby
choco install -y screenhero
choco install -y sharpkeys
choco install -y slack
#choco install -y sqlyog
choco install -y sysinternals
choco install -y terminals
#choco install -y UrlRewrite
choco install -y vlc
