# -*- shell-script -*-
## Read for interactive shells

# Handle dumb terms
[[ $TERM == "dumb" ]] && unsetopt zle && PS1='$ ' && return

## profiling: uncomment to enable profiling
# zmodload zsh/zprof

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

## force readline keybinds
bindkey -e

## antigen
# To manage plugins, update `zsh.d/plugins.txt` then run `bin/antigen`
# to regenerate this file.
source ~/.zsh.d/plugins.zsh

## Pure prompt
PURE_GIT_PULL=0

autoload -U compinit && compinit

## aliases
if command -v exa >/dev/null 2>&1; then
  alias ls='exa'
  alias ll='exa -lah'
fi

if command -v bat >/dev/null 2>&1; then
  export PAGER='bat'
  export MANPAGER='bat'
  alias cat='bat'
fi

alias vim='nvim'
alias e='emacsclient -n'
alias p='pipenv run'
alias m='p python manage.py'
alias sp='m shell_plus'
alias tf='terraform'

if command -v rbenv >/dev/null 2>&1; then
  eval "$(rbenv init -)"
fi

if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

if [[ -d $NVM_DIR ]]; then
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
fi

[ -f $HOME/.fzf.zsh ] && source ~/.fzf.zsh

[ -f $HOME/.profile-private.sh ] && source ~/.profile-private.sh

# zprof
[ -f "${HOME}/.jellyfish/environment" ] && source "${HOME}/.jellyfish/environment"
