# -*- shell-script -*-

export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

export ZSH=$HOME/.oh-my-zsh

if [[ `uname` == "Linux" ]]; then
    ZSH_THEME="imajes"
else
    ZSH_THEME="agnoster"    
fi

if [[ `uname` == "Linux" ]]; then
    plugins=(git zsh-completions tmux dnf debian)
else
    plugins=(osx brew git zsh-completions tmux mix aws ssh lein rbenv bundler gem ruby)
fi

autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

export SSH_KEY_PATH="~/.ssh/rsa_id"

alias bu="brew update && brew upgrade"

export DEFAULT_USER="asm"

if [[ -f ~/.iterm2_shell_integration.zsh ]]; then
    source ~/.iterm2_shell_integration.zsh
fi

if command -v rbenv >/dev/null 2>&1; then
   eval "$(rbenv init -)"
fi

if [[ -d ~/proj/go ]]; then
    export GOPATH="$HOME/proj/go"
fi


# if [[ -d /usr/local/share/zsh-completions ]]; then
#     fpath = (/usr/local/share/zsh-completions $fpath)
# fi
