# -*- shell-script -*-

export PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH

export LSCOLORS='exfxcxdxbxegedabagacad'
export CLICOLOR=true

bindkey -e

#export EDITOR='code'
export EDITOR='mvim -f --nomru -c "au VimLeave * !open -a iTerm"'

if [[ -d ~/.zplug ]]; then
  export ZPLUG_HOME=~/.zplug
  source $ZPLUG_HOME/init.zsh

  # zplug "zsh-users/zsh-history-substring-search"
  zplug "zsh-users/zsh-completions"
  zplug "zsh-users/zsh-syntax-highlighting"
  zplug "zsh-users/zsh-autosuggestions"
  zplug "plugins/history", from:oh-my-zsh
  zplug "rupa/z", use:z.sh

  zplug "denysdovhan/spaceship-zsh-theme", use:spaceship.zsh, from:github, as:theme

  # Install plugins if there are plugins that have not been installed
  if ! zplug check; then
      printf "Install? [y/N]: "
      if read -q; then
          echo; zplug install
      fi
  fi
  
  zplug load
fi

# Spaceship prompt config
SPACESHIP_PROMPT_SYMBOL="λ"
SPACESHIP_DOCKER_SHOW=false
SPACESHIP_VENV_SHOW=false
SPACESHIP_CONDA_SHOW=false

autoload -U compinit && compinit

export SSH_KEY_PATH="$HOME/.ssh/rsa_id"

# vendor exports
export HOMEBREW_NO_ANALYTICS=1
export VAGRANT_DEFAULT_PROVIDER="parallels"

alias bu="brew update && brew upgrade"
alias gs="git s"
alias gd="git d"
alias m="python manage.py"

if [[ -f $HOME/.iterm2_shell_integration.zsh ]]; then
    source $HOME/.iterm2_shell_integration.zsh
fi

if command -v rbenv >/dev/null 2>&1; then
    eval "$(rbenv init -)"
fi

if [[ -d $HOME/.pyenv ]]; then
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"

    export PYENV_VIRTUALENV_DISABLE_PROMPT=1
fi

if [[ -d $HOME/proj/go ]]; then
    export GOPATH="$HOME/proj/go"
    export PATH="$GOPATH/bin:$PATH"
fi

[ -f $HOME/.profile-private.sh ] && source ~/.profile-private.sh
[ -f $HOME/.fzf.zsh ] && source ~/.fzf.zsh

