- clean:
  - '~'

- create:
  - ~/.local/share
  - ~/proj
  - ~/tmp

- link:
    ~/.config/nix:                     etc/nix
    ~/.config/home-manager:            etc/home-manager
    ~/.doom.d:                         etc/doom-emacs
    # ~/.emacs.d:                      etc/emacs-prelude

- shell:
  - |
    [ -d ~/.pyenv ] || git clone https://github.com/pyenv/pyenv.git ~/.pyenv
