- clean:
  - '~'

- create:
  - ~/.local/share
  - ~/.ssh
  - ~/.tmux
  - ~/.tmux/plugins
  - ~/proj
  - ~/tmp

- link:
    ~/bin:                             scripts
    ~/.config/nix:                     etc/nix
    ~/.config/nixpkgs:                 etc/nixpkgs
    ~/.doom.d:                         etc/doom-emacs
    # ~/.emacs.d:                      etc/emacs-prelude
    ~/.zlogout:                        etc/zlogout
    ~/.zsh.d:                          etc/zsh.d
    ~/.zsh_plugins.txt:                etc/zsh_plugins.txt
    ~/.zshrc:                          etc/zshrc
    ~/.zshenv:                         etc/zshenv

- shell:
  - |
    OS_CONFIG="os/$(uname | tr '[:upper:]' '[:lower:]')/default.yml"
    if [[ -f $OS_CONFIG ]]; then
      ./submodules/dotbot/bin/dotbot -c $OS_CONFIG
    fi
  - curl -sfLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  - |
    [ -d ~/.tmux/plugins/tpm ] || git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  - |
    [ -d ~/.pyenv ] || git clone https://github.com/pyenv/pyenv.git ~/.pyenv
  - |
    [ -d ~/.asdf ] || git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch v0.8.0
  - ~/.asdf/bin/asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git || exit 0
  - ~/.asdf/bin/asdf plugin-add terraform https://github.com/asdf-community/asdf-hashicorp.git || exit 0
  - ~/.asdf/bin/asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git || exit 0
  - chmod 0700 ~/.ssh
  - chmod 0600 ~/.ssh/config
