---
- name: Install packages
  dnf:
    name: "{{ item }}"
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"
  loop:
    - ripgrep
    - fzf
    - direnv
    - "https://downloads.slack-edge.com/linux_releases/slack-3.4.2-0.1.fc21.x86_64.rpm"
    - racket

- name: Install alacritty COPR repo
  shell: dnf copr --assumeyes enable pschyska/alacritty
  args:
    warn: no
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Install alacritty
  dnf:
    name: alacritty
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Check alacritty config dir exists
  stat: path="{{ dotfiles_home }}/.config/alacritty"
  register: alacritty_dir

- name: Create alacritty config dir
  file:
    dest: "{{ dotfiles_home }}/.config/alacritty"
    state: directory
  when: alacritty_dir.stat.exists == False

- name: Link alacritty config
  file:
    src: "{{ dotfiles_root }}/roles/linux/files/alacritty.yml"
    dest: "{{ dotfiles_home }}/.config/alacritty/alacritty.yml"
    state: link

- name: Install kitty COPR repo
  shell: dnf copr --assumeyes enable gagbo/kitty-latest
  args:
    warn: no
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Install kitty
  dnf:
    name: kitty
    state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"
