---
- name: Install Git
  dnf:
          name: git
          state: latest
  become: yes
  become_method: sudo
  when: ansible_os_family == "RedHat"

- name: Link gitignore
  file:
          src: "{{dotfiles_root}}/roles/git/files/gitignore_global"
          dest: "{{dotfiles_home}}/.gitignore_global"
          state: link
          force: yes

- name: Check if gitconfig exists
  stat: path="{{dotfiles_home}}/.gitconfig"
  register: gitconfig

- name: Back up gitconfig
  command: mv ~/.gitconfig ~/.gitconfig.bak
  args:
    creates: "{{dotfiles_home}}/.gitconfig.bak"
  when: gitconfig.stat.exists

- name: Render gitconfig
  template:
          src: "gitconfig.j2"
          dest: "{{dotfiles_home}}/.gitconfig"
