#!/usr/bin/env bash
# -*- shell-script -*-

echo "setting up OS X configuration"

SETUP_HOSTNAME="asm-mbp"

echo "setup time machine"
sudo defaults write /Library/Preferences/com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true

echo "setup finder"
chflags nohidden ~/Library
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true
defaults write com.apple.finder ShowStatusBar -bool true
defaults write -g NSDocumentSaveNewDocumentsToCloud -bool false
defaults write com.apple.finder NewWindowTarget -string "PfLo"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

echo "disable autocorrect"
defaults write -g NSAutomaticSpellingCorrectionEnabled -bool false

echo "disable press-and-hold"
defaults write -g ApplePressAndHoldEnabled -bool false

echo "setup key repeat"
defaults write NSGlobalDomain KeyRepeat -int 0.1
defaults write NSGlobalDomain InitialKeyRepeat -int 15

echo "setup safari"
defaults write com.apple.Safari IncludeInternalDebugMenu -bool true
defaults write com.apple.Safari IncludeDevelopMenu -bool true 
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true 
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true 
defaults write -g WebKitDeveloperExtras -bool true

echo "set hostname to $HOSTNAME"
sudo scutil --set ComputerName $SETUP_HOSTNAME
sudo scutil --set HostName $SETUP_HOSTNAME
sudo scutil --set LocalHostName $SETUP_HOSTNAME
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string $SETUP_HOSTNAME

