#!/bin/sh

if [[ ! -f ~/.vim/autoload/plug.vim ]]; then
	echo "Installing plug to ~/.vim/autoload/plug.vim"
	curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
	echo "Plug already installed, skipping..."
fi
