#!/usr/bin/env bash
# -*- shell-script -*-

echo 'Setting up Visual Studio Code'

[ -f ~/Library/Application\ Support/Code/User/settings.json ] && mv ~/Library/Application\ Support/Code/User/settings.json ~/Library/Application\ Support/Code/User/settings.json.bak
[ -d ~/Library/Application\ Support/Code/User/snippets ] && mv ~/Library/Application\ Support/Code/User/snippets ~/Library/Application\ Support/Code/User/snippets.bak

VSCODE_BASE_PATH="`pwd`/vscode"
SETTINGS_JSON_PATH=$VSCODE_BASE_PATH/settings.json
SNIPPETS_PATH=$VSCODE_BASE_PATH/snippets

echo "Link $SETTINGS_JSON_PATH => ~/Library/Application\ Support/Code/User/settings.json"
ln -sf $SETTINGS_JSON_PATH ~/Library/Application\ Support/Code/User/settings.json

echo "Link $SNIPPETS_PATH => ~/Library/Application\ Support/Code/User/snippets"
ln -sf $SNIPPETS_PATH ~/Library/Application\ Support/Code/User/snippets

echo 'Done'
