#!/usr/bin/env bash
mkdir -p ~/Library/Developer/Xcode/UserData/FontAndColorThemes
ln -s ~/proj/vendor/dracula-theme/xcode/Dracula.dvtcolortheme ~/Library/Developer/Xcode/UserData/FontAndColorThemes/Dracula.dvtcolortheme
