# -*- shell-script -*-
if [ -d /opt/homebrew ] && [[ "$(arch)" == 'arm64' ]]; then
  alias brew='/opt/homebrew/bin/brew'
  alias bu="brew update && brew upgrade"
  # export PATH="/opt/homebrew/bin:$PATH"
  eval "$(/opt/homebrew/bin/brew shellenv)"
elif type brew &>/dev/null; then
  BREWROOT="$(brew --prefix)"
  FPATH="$$BREWROOT/share/zsh/site-functions:$FPATH"
  export PATH="$BREWROOT/sbin:$PATH"
  export LDFLAGS="-L$BREWROOT/lib -L$BREWROOT/opt/openssl/lib -L$BREWROOT/opt/zlib/lib"
  export CPPFLAGS="-I$BREWROOT/include -I$BREWROOT/opt/openssl/include -I$BREWROOT/opt/zlib/include"
  export PKG_CONFIG_PATH="$BREWROOT/lib/pkgconfig:$BREWROOT/opt/openssl/lib/pkgconfig:$BREWROOT/opt/zlib/lib/pkgconfig"
  alias bu="brew update && brew upgrade"
fi

if type xcrun &>/dev/null; then
  export SDKROOT=$(xcrun --show-sdk-path)
fi

# Use `say` to have the computer say done/error when a command completes
notify_internal () {
  command=$1
  res=$2

  # osascript -e 'display notification "'$res': '$command'" with title "Command '$res'"'
  say $res
}

alias a='f() { {eval "$@" && notify_internal "$*" Done} || notify_internal "$*" Error};f'
