#!/usr/bin/env bash
# -*- shell-script -*-

set -euo pipefail

venv_path="$(poetry show -v | grep 'Using virtualenv' | sed -e 's/Using virtualenv: //')"

if test -z "$venv_path"; then
  exit 1
fi

echo "Removing virtualenv: $venv_path"
rm -rf "$venv_path"
