---
- name: Remove Distro Docker packages
  dnf:
    name: "{{ item }}"
    state: absent
  loop:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
  become: yes

- name: Install dnf-plugins-core
  dnf:
    name: dnf-plugins-core
    state: present
  become: yes

- name: Add Docker DNF repo
  shell: 'dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo'
  args:
    warn: no
  become: yes

- name: Install Docker
  dnf:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
  become: yes

- name: Start Docker
  systemd:
    state: started
    name: docker
  become: yes

- name: Add user to Docker group
  user:
    name: "{{ ansible_env.USER }}"
    groups: docker
    append: yes
  become: yes

- name: Install MicroK8S
  snap:
    name: microk8s
    classic: yes
  become: yes
