---
- name: Install ruby-build dependencies
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - bzip2
    - openssl-devel
    - libyaml-devel
    - libffi-devel
    - readline-devel
    - zlib-devel
    - gdbm-devel
    - ncurses-devel
  become: yes
  become_method: sudo

- name: Check rbenv install
  stat: path="{{ dotfiles_home }}/.rbenv"
  register: rbenv_dir

- name: Install rbenv
  git:
    repo: 'https://github.com/rbenv/rbenv.git'
    dest: "{{ dotfiles_home }}/.rbenv"
  when: rbenv_dir.stat.exists == False

- name: Check ruby-build install
  stat: path="{{ dotfiles_home }}/.rbenv/plugins/ruby-build"
  register: ruby_build_dir

- name: Install ruby-build plugin
  git:
    repo: 'https://github.com/rbenv/ruby-build.git'
    dest: "{{ dotfiles_home }}/.rbenv/plugins/ruby-build"
  when: ruby_build_dir.stat.exists == False

- name: Install Ruby versions
  shell: |
    export PATH="{{ dotfiles_home }}/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv install {{ item }} || true # Ignore already installed versions
  args:
    executable: /bin/bash
  loop: '{{ ruby_versions }}'

- name: Set Ruby global version
  shell: |
    export PATH="{{ dotfiles_home }}/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    rbenv global {{ ruby_global }}
  args:
    executable: /bin/bash

- name: Install Ruby tools
  shell: |
    export PATH="{{ dotfiles_home }}/.rbenv/bin:$PATH"
    eval "$(rbenv init -)"
    gem install {{ item }}
    rbenv rehash
  args:
    executable: /bin/bash
  loop:
    - pry
    - rake

- name: Link ruby config files
  file:
    src: "{{ dotfiles_root }}/roles/ruby/files/{{ item }}"
    dest: "{{ dotfiles_home }}/.{{ item }}"
    state: link
    force: yes
  loop:
    - gemrc
    - irbrc
